server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    hikari:
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sakila?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false&rewriteBatchedStatements=true
        username: root
        password: 123qwe
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/sakila?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false&rewriteBatchedStatements=true
        username: root
        password: 123456


#  shardingsphere:
#    datasource:
#      names: ds-master,ds-slave
#      ds-master:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/sakila?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false&rewriteBatchedStatements=true
#        username: root
#        password: 123456
#      ds-slave:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3307/sakila?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false&rewriteBatchedStatements=true
#        username: root
#        password: 123456
#    sharding:
#      tables:
#        user_info:
#          actual-data-nodes: ds-master-$->{0..1}.user_info_$->{0..1}
#          table-strategy:
#            inline:
#              sharding-column: id
#              algorithm-expression: user_info_$->{id % 2}
#          key-generator:
#            column: id
#            type: SNOWFLAKE
#      default-database-strategy:
#        inline:
#          sharding-column: id
#          algorithm-expression: ds-master-$->{id % 2}
#    props:
#      sql:
#        show: false


mybatis-plus:
  configuration:
    #控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl